FROM ubuntu:18.04

LABEL tool="multiqc"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apt-get update -y && apt-get install -y python3 \
	python3-pip \
	git && \
	python3 -m pip install --upgrade pip setuptools && \
	python3 -m pip install git+https://github.com/ewels/MultiQC.git 

ENV	LC_ALL C.UTF-8
ENV	LANG C.UTF-8


ENTRYPOINT ["multiqc"]
