FROM alpine:3.16

LABEL tool="plot_peak_distance"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache R bash font-noto && \
    Rscript -e 'install.packages("optparse",repos = "http://cran.us.r-project.org")' 

ADD bin/plot-distances.R /usr/local/bin

CMD ["plot-distances.R"]
