FROM rocker/r-ver:4.2.3

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

RUN install2.r optparse ggplot2 reshape2 wig

ADD bin/plot_experimental_barcode_distribution.R /usr/local/bin
ADD bin/plot-distances.R /usr/local/bin
ADD bin/RNA_subtypes_barcharts.R /usr/local/bin
ADD bin/visualize_strand_distribution.R /usr/local/bin
ADD bin/wig_file_statistics.R /usr/local/bin
ADD bin/generate-peak-height-histogram.R /usr/local/bin

CMD ["/bin/bash"]
