FROM alpine:latest

LABEL tool="RNA_species_barchart_generation"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache R R-dev \
	bash \
	make \
	musl-dev \
	g++ \
	gcc \
	zlib zlib-dev && \
    Rscript -e 'install.packages("BiocManager",repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("optparse",repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("ggplot2",repos = "http://cran.us.r-project.org")' && \
    apk del R-dev make musl-dev g++ gcc zlib-dev openssl-dev zlib-dev brotli-dev curl-dev openblas-dev libpng-dev \
        icu-dev libedit-dev ncurses-dev pcre2-dev readline-dev xz-dev bzip2-dev libc-dev nghttp2-dev pcre2-dev

ADD bin/plot_experimental_barcode_distribution.R /usr/local/bin

CMD ["plot_experimental_barcode_distribution.R"]
