FROM alpine:latest

LABEL tool="peak_distance"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache python3 py3-numpy bash

ADD bin/wig_files_writer.py /usr/local/bin
ADD bin/peak-distance.py /usr/local/bin
ADD bin/wig2-to-wig.py /usr/local/bin

CMD ["peak-distance.py"]
