FROM alpine:3.17

LABEL tool="sequence_extraction"

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

RUN apk update && apk add --no-cache python3 py3-numpy bash && \
    apk add py3-biopython --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

ADD bin/wig_files_writer.py /usr/local/bin
ADD bin/sequence-extraction.py /usr/local/bin
ADD bin/wig2-to-wig.py /usr/local/bin

CMD ["sequence-extraction.py"]