FROM alpine:latest

LABEL tool="merge-wig"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk add --no-cache bash

ADD bin/merge-wig.py /usr/local/bin

CMD ["merge-wig.py"]
