FROM alpine:3.16

LABEL tool="merge-wig"

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

RUN apk update && apk add --no-cache python3 \
	bash 

ADD bin/merge-wig.py /usr/local/bin
ADD bin/wig2-to-wig.py /usr/local/bin
ADD bin/wig_files_writer.py /usr/local/bin

CMD ["merge-wig.py"]
