FROM alpine:3.16

LABEL tool="RNA_species_distribution"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache python3 \
	bash

ADD bin/calc-RNA-subtypes-distribution.py /usr/local/bin

CMD ["calc-RNA-subtypes-distribution.py"]
