FROM alpine:3.16

LABEL tool="RNA_species_barchart_generation"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache R font-noto \
	bash \
	make && \
    Rscript -e 'install.packages("optparse",repos = "http://cran.us.r-project.org")' && \
    apk del make
	

ADD bin/RNA_subtypes_barcharts.R /usr/local/bin

CMD ["RNA_subtypes_barcharts.R"]
