FROM alpine:latest

LABEL tool="trim_galore"
LABEL tool.version="0.6.7"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

#install cutadapt
RUN apk add --no-cache python3 \
	python3-dev \
	py3-pip \
	g++ \
	make \
	unzip \
	perl \
	bash && \
	python3 -m pip install cutadapt==4.1

#install trim_galore	
ARG FILE=0.6.7.zip
ARG TMPDIR=/opt

RUN wget https://github.com/FelixKrueger/TrimGalore/archive/$FILE -O $TMPDIR/$FILE && \
	unzip $TMPDIR/$FILE -d $TMPDIR && \
	rm $TMPDIR/$FILE && \
	chmod 755 $TMPDIR/TrimGalore-0.6.7/trim_galore
	
ENV PATH $TMPDIR/TrimGalore-0.6.7:$PATH

ENTRYPOINT ["trim_galore"]
#RUN apt-get install 
#RUN wget --no-check-certificate https://github.com/FelixKrueger/TrimGalore/archive/0.6.7.zip
