FROM alpine:3.16

LABEL tool="samtools"
LABEL tool.version="1.16.1"

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

ARG FILE=samtools-1.16.1.tar.bz2
ARG TMPDIR=/opt

RUN apk update && apk add --no-cache bash \
	g++ \
	gcc \
	make \
	musl-dev \
        zlib-dev && \
	wget -q https://github.com/samtools/samtools/releases/download/1.16.1/samtools-1.16.1.tar.bz2 -O $FILE && \
        tar xf $FILE && \
        cd samtools-1.16.1 && \
        ./configure --prefix=/opt/samtools --disable-libcurl --disable-bz2 --disable-lzma --without-curses && \
        make install && \
        rm -rf $FILE samtools-1.16.1 /opt/samtools/share && \
    apk del g++ gcc make musl-dev zlib-dev 

ENV PATH /opt/samtools/bin:$PATH

CMD ["samtools"]
