FROM alpine:3.17

LABEL tool="subread"
LABEL tool.version="2.0.3"

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

ARG FILE=subread-2.0.3-source.tar.gz
ARG TMPDIR=/opt

RUN apk update && apk add --no-cache bash \
	gcc \
	make \
	musl-dev \
	zlib-dev && \
	wget -q https://sourceforge.net/projects/subread/files/subread-2.0.3/$FILE -O $TMPDIR/$FILE && \
	tar -xf $TMPDIR/$FILE -C $TMPDIR && \
	cd $TMPDIR/subread-2.0.3-source/src && \
	make -f Makefile.Linux featureCounts && \
        cp featureCounts /usr/bin && \
        rm -rf $TMPDIR/$FILE $TMPDIR/subread-2.0.3-source/ && \
   apk del gcc make musl-dev zlib-dev

