FROM alpine:latest

LABEL tool="multiqc"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache python3 \
        py3-matplotlib \
        py3-pip py3-numpy py3-kiwisolver \
        bash && \
        python3 -m pip install multiqc==1.12

ENV	LC_ALL C.UTF-8
ENV	LANG C.UTF-8


ENTRYPOINT ["multiqc"]
