FROM alpine:latest

LABEL tool="plot_peak_distance"

MAINTAINER Patrick Barth <patrick.barth@computational.bio.uni-giessen.de>

RUN apk update && apk add --no-cache R bash && \
    Rscript -e 'install.packages("BiocManager",repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("optparse",repos = "http://cran.us.r-project.org")' 

ADD bin/plot-distances.R /usr/local/bin

CMD ["plot-distances.R"]
