FROM alpine:3.16

LABEL tool="FASTQC"
LABEL tool.version="0.11.9"

LABEL maintainer="patrick.barth@computational.bio.uni-giessen.de"

ARG FILE=fastqc_v0.11.9.zip
ARG TMPDIR=/opt

RUN apk update && apk add --no-cache \
	wget \
	perl \
	unzip \
        bash \
	openjdk17 fontconfig font-dejavu-sans-mono-nerd

RUN	wget -q http://www.bioinformatics.babraham.ac.uk/projects/fastqc/$FILE -O $TMPDIR/$FILE && \
	unzip $TMPDIR/$FILE -d $TMPDIR && \
	rm $TMPDIR/$FILE && \
	chmod 755 $TMPDIR/FastQC/fastqc

ENV PATH ${TMPDIR}/FastQC:$PATH

CMD ["fastqc"]
